version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: ava
    versions:
    - 3.14.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
