language: node_js
node_js:
- 'node'

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=checkstyle

install: 
- npm install
- npm install -g codecov

script:
- if [ "$TEST_SUITE" == "test" ]; then npm run coverage && codecov; fi
- if [ "$TEST_SUITE" == "checkstyle" ]; then npm run checkstyle; fi